project:
  type: book

book:
  title: "Big Book of R"
  author: "Oscar Baruffa"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  image: cover.png

  cover-image: cover1.png
  sidebar:
    search: true
    style: floating
    collapse-level: 1
    border: true
  
  page-footer: 
    border: false
    background: light
    left: | 
      Big Book of R - Oscar Baruffa
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - 010-start_here.qmd
    - 015-book_clubs.qmd
    - chapters/Career and Community.qmd
    - chapters/API.qmd
    - chapters/Archeology.qmd
    - chapters/Art.qmd
    - chapters/Big Data.qmd
    - chapters/Blogdown.qmd
    - chapters/Bookdown.qmd
    - chapters/Data Science.qmd
    - chapters/Data Visualization.qmd
    - chapters/Data Databases and Engineering.qmd
    - chapters/Economics.qmd
    - chapters/Espa√±ol.qmd
    - chapters/Field Specific.qmd
    - chapters/Finance.qmd
    - chapters/Geospatial.qmd
    - chapters/Getting Cleaning and Wrangling Data.qmd
    - chapters/Journalism.qmd
    - chapters/Life Sciences.qmd
    - chapters/Machine Learning.qmd
    - chapters/Network Analysis.qmd
    - chapters/Packages.qmd
    - chapters/People Analytics.qmd
    - chapters/Psychology.qmd
    - chapters/R Package Development.qmd
    - chapters/R Programming.qmd
    - chapters/Reports.qmd
    - chapters/Shiny.qmd
    - chapters/Social Science.qmd
    - chapters/Sport Analytics.qmd
    - chapters/Statistics.qmd
    - chapters/Teaching.qmd
    - chapters/Text Analysis.qmd
    - chapters/Time Series Analysis and Forecasting.qmd
    - chapters/Version Control.qmd
    - chapters/Workflow.qmd
    - chapters/Other Compendiums.qmd
  
format:
  html:
    toc: true
    toc-depth: 5
    theme:
      light:
        - flatly
        - bigbook.scss
        # - custom.scss
      dark:
        - darkly
    include-in-header:
      - plausible-analytics.html
      - social.html
    include-after-body: footer.html
    edit: https://github.com/oscarbaruffa/BigBookofR/edit/main/%s
